### ISSUE TITLE
Sed ne remplace pas tous les liens .MD en .html

### ISSUE THREAD

**Issue by sveinburne** [dirtylab/site-scripts#1]
**Capture**
``` Shell
find . -type f -regextype sed -regex ".*/.*\.\(MD\|md\)"
```
**Remplacement**
``` Shell
sed -i.bak -e 's/\([A-Za-z0-9.\-_]\{1,\}\)\.MD/\1.html/g' $f
```
[Exemple d'omission sur les liens de cette page !](http://dirtylab.github.io/THEORIE/PISTES.html)

**Comment by Frosty-Z** [comment]
(copie du tchat)

ok fixé. un diff avec le précédent commit montre que le ​**_config.yml**​ contenait à nouveau "localhost:4000" comme url racine au lieu de "dirtylab.github.io" + effectivement de nombreux fichiers ​**.MD**​ dont les liens étaient toujours en ​**.MD**​ au lieu de ​**.html**​ (je ne comprends pas ??)

merci d'essayer de lancer un `./1_process.sh` sur ton environnement et de voir si les **.MD** de `tmp_site/_includes` (`PISTES` entre autres), ont des liens en **.html** ou en **.MD**

**Comment by Frosty-Z** [comment]
Problème d'environnement (OK sur Cygwin, HS sur Ubuntu) confirmé par @sveinburne sur le tchat.

Je vais tenter de faire en sorte que les scripts fonctionnent sur une VM Ubuntu plutôt que sur Cygwin.

**Comment by Frosty-Z** [comment]
@sveinburne: devrait être corrigé. Fonctionne chez moi sur Cygwin et une VM Ubuntu.
Apparemment ce genre de surprise peut arriver sur des expressions régulières qui fonctionnent sur Mac OS mais pas Ubuntu.
Il faut mettre le "-" en tout début ou toute fin de `[...]`. Tordu.
Voir : http://stackoverflow.com/questions/16637432/sed-error-invalid-range-end

**Comment by sveinburne** [comment]
Yes ça fonctionne! Ah les fichues regex qui ne sont pas uniformisées... -_- Merci en tout cas :)
