### ISSUE TITLE
Intégration continue

### ISSUE THREAD

**Issue by Frosty-Z** [dirtylab/site-scripts#10]
Suite à une proposition de @sveinburne sur Slack : il serait bon d'automatiser le "process de build/deploiement" du site que je fais actuellement de temps en temps depuis mon PC, à l'aide d'un service d'intégration continue comme https://travis-ci.org

Les scripts de build/déploiement + éléments mise en forme (templates Jekyll, CSS, images...) se trouvent ici : https://github.com/dirtylab/site-scripts

**Comment by Frosty-Z** [comment]
Lien utile fourni par @sveinburne sur le tchat

https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

**Comment by Frosty-Z** [comment]
Je mets ce lien très intéressant aussi :
https://medium.com/@nthgergo/publishing-gh-pages-with-travis-ci-53a8270e87db#.2txd8wyk3

**Comment by Frosty-Z** [comment]
Je crois qu'on y est ! Mon premier build+deploy sur Travis. Emotion :joy: 

Je réalise aussi que le build+deploy devrait être aussi lancé automatiquement quand on a un commit sur le repo **sveinburne/lets-play-science**, puisque le build récupère le contenu de ce repo... des avis ?

**Comment by sveinburne** [comment]
Peut être avec une deuxième intégration continue sur travis (repo sveinburne/lets-play-science) qui génère un build on demand : https://docs.travis-ci.com/user/triggering-builds

**Comment by Frosty-Z** [comment]
@sveinburne J'aimerais essayer une technique très proche de ce que tu décris. Par contre je n'ai pas les droits pour demander à Travis d'activer les builds sur le repo lets-play-science. Du coup, soit je te laisse faire l'activation (et si possible me permettre de voir les infos des builds lancés), soit il faut forker sur l'organisation DirtyLab :wink:

**Comment by sveinburne** [comment]
@Frosty-Z allez je pense qu'il faut passer tout sur **dirtylab/**, alors autant le faire maintenant! Pour bouger les issues : https://github-issue-mover.appspot.com/

**Comment by Frosty-Z** [comment]
Dépôt + issues déplacées, merci @sveinburne 

Le "trigger automatique" depuis **dirtylab/wiki** est fait !
Un commit sur ce dépôt va également déclencher le bazar de build + deploy depuis **dirtylab/site-scripts**.

Je ferme l'issue ! :wink:
