### ISSUE TITLE
Workflow client structuré avec Npm + Grunt + webpack

### ISSUE THREAD

**Issue by sveinburne** [dirtylab/site-scripts#14]

**Comment by sveinburne** [comment]
@Frosty-Z  ça fonctionne avec Travis! 
Seul problème, j'ai du commit les `node_modules`, car vu toutes les "devDependencies" déclarées avec npm, ça faisait un temps de build de 1m40s !!! Là je suis rendu à 11s, ce qui est encore "acceptable". 
J'attends de voir avec toi si la structure + node_modules te convient et je merge avec master. 

Actuellement sur le site dirtylab.github.io tu devrais voir un petit message se charger dans la console, c'est juste un test.

J'ai aussi pas mal mis à jour le README.MD pour présenter un peu les outils côté client.

**Comment by Frosty-Z** [comment]
Bah, tant que ça ne donne pas des temps de "git clone" ou autre trop longs, je n'y vois pas d'inconvénient, faut bien trouver des compromis.

Super la restructuration du README, j'irai regarder le détail de packages que tu as soigneusement sélectionnés dès que le temps me le permettra.

Pas de souci pour moi pour mettre dans master :wink:

**Comment by sveinburne** [comment]
@Frosty-Z Cool :)
Je vais me renseigner si on peut lancer des scripts par branche sur travis
: on pourrait alors avoir une branche "dev" dans laquelle on compile tout notre bordel, et une branche "intégration" qui ne sert qu'à automatiser le redéploiement jekyll pour les nouveaux fichiers .MD publiés. 
Le merge est réalisé, donc je ferme!
