### ISSUE TITLE
Harmonisation du dépot

### ISSUE THREAD

**Issue by sveinburne** [dirtylab/site-scripts#24]
Pour rendre le dépot un peu plus lisible, je propose la structure suivante : 

* `client/`
  * `es6/` (anciennement `client`)
  * `package.json`
  * `gruntfile.js`
  * `webpack.config.js`
* `jekyll/` (anciennement `jekyll_stuff`)
* `scripts/`
  * `build.sh` (anciennement `1_prepare.sh`)
  * `push.sh` (anciennement `2_push.sh`)
  * `travis.sh` (anciennemnt `deploy_from_travis.sh`)
  * `fixlinks.php`
  * `emojize/`
* `README.MD`
* `LICENSE`

**Comment by Frosty-Z** [comment]
Ok pour moi, par contre évidemment bien penser à mettre à jour toutes les "références" concernées vers les fichiers déplacés/renommés, que ce soit dans le README, dans d'autres scripts ou fichiers de config.
