### ISSUE TITLE
Intégration de prose.io cassée ?

### ISSUE THREAD

**Issue by Frosty-Z** [dirtylab/site-scripts#26]
Lorsque j'essaie de modifier un `.MD` depuis [dirtylab.github.io](http://dirtylab.github.io) à l'aide de **prose.io**, je saisis une description et je clique sur **commit**, j'obtiens alors une erreur **"Not found"**... (essayé avec `PRATIQUE/OUTILS.MD` et `PRATIQUE/SYNTHESE_YOUTUBE.MD`)

La console JS dit : 
`Failed to load resource: the server responded with a status of 404 (Not Found)`
`https://api.github.com/repos/dirtylab/wiki/contents/PRATIQUE/SYNTHESE_YOUTUBE.MD?ref=master`
Pourtant quand j'ouvre un nouveau tab avec cette URL, j'obtiens un genre de réponse JSON tout ce qu'il y a de propre...

Et là je sèche... D'autant que [la seule question StackOverflow traitant de ce problème](http://stackoverflow.com/questions/34040965/prose-io-not-found-error-message) n'a aucune réponse (ça peut être l'occasion de se faire un peu de réputation :wink: )

**Comment by sveinburne** [comment]
Ah mince, j'étais tombé sur ce problème il y a quelques jours et j'ai pensé que c'était passager! J'vais regarder leur github.

**Comment by sveinburne** [comment]
[Je suis tombé sur cette issue](https://github.com/prose/prose/issues/898) et effectivement, en désactivant / réactivant l’autorisation de prose.io sur github ça a fonctionné! Qu'en est-t-il pour toi ?

**Comment by Frosty-Z** [comment]
Je viens de faire un test de modif sur le fichier "VP forum propositions Youtube" ou encore le fichier "Synthèse Youtube". Lors du clic sur **commit**, j'obtiens cette erreur : *Error while loading data from Github. This might be a temporary issue. Please try again later.*

**Comment by sveinburne** [comment]
Tu as désactivé / réactivé l'intégration de prose.io d'abord ?

**Comment by Frosty-Z** [comment]
Je n'ai rien fait de particulier... Quelle est la manip pour faire ce que tu dis ? Désolé si je suis passé à côté d'un truc évident...

**Comment by sveinburne** [comment]
Pas de soucis, j'aurais pu expliquer un peu plus :) D'après le post, c'est un problème lié au token fournis par github à prose.io. Il faut donc le regénérer, et pour celà pas d'autre choix que de [désinstaller l'application prose.io sur ton github](https://github.com/settings/applications), puis se rendre sur prose.io (page d'accueil) et cliquer sur "authorize on github" !

**Comment by Frosty-Z** [comment]
C'est désormais OK, merci.

Par contre ça signifie que le "visiteur lambda" qui n'est pas encore authentifié sur GitHub et n'a pas fait la manip "authorize on GitHub" pour **prose.io** va se retrouver avec ce genre d'erreur obscure... 

Bon je confirme en essayant depuis un autre navigateur... Pas très friendly tout ça... :disappointed: 
Quand je m'authentifie sur GitHub, malgré le fait d'avoir déjà procédé au "authorize on GitHub", j'ai la même erreur *error while loading data from Github...* :-1: 

Je dirais que le minimum serait de détecter que la création d'une session GitHub et/ou le "authorize on GitHub" pour **prose.io** n'ont pas encore été faits, en informer l'utilisateur et lui indiquer la démarche à suivre... A l'occasion j'ouvre une issue exprès pour ça. En attendant on peut fermer celle-ci je pense.

**Comment by sveinburne** [comment]
Yes je suis d'accord, pas très user friendly. On trouvera une solution!
