### ISSUE TITLE
Lien d'édition vers prose.io et github pour chaque fichier issue de markdown

### ISSUE THREAD

**Issue by sveinburne** [dirtylab/site-scripts#5]
Proposé par @Frosty-Z

**Comment by Frosty-Z** [comment]
Suite à une suggestion de @sveinburne sur le tchat, un projet permettant d'utiliser GitHub pages quasiment comme un wiki a vu le jour, à creuser : https://github.com/wiki-hub/wiki-hub

**Comment by Frosty-Z** [comment]
Dans un "3ème temps", le truc de malade serait de proposer par défaut un mode WYSIWYG (avec toujours la possibilité de modifier le source Markdown directement bien sûr). Dans la discussion que tu m'as montrée https://talk.jekyllrb.com/t/an-idea-for-front-end-editing-in-jekyll-via-the-github-api-and-web-based-markdown-editors/737 
Le gars qui a créé la discussion a parlé de [Dillinger](http://dillinger.io) et [StackEdit](https://stackedit.io)
Il y a peut être aussi [Hallo.js](http://hallojs.org/demo/markdown/)

**Comment by sveinburne** [comment]
Fait!

**Comment by Frosty-Z** [comment]
Trop chouette !!! Bravo.
J'aurais des remarques sur le graphisme mais pas prioritaires, on verra ça quand on aura des contributeurs "vrais graphistes" ;-)
