### ISSUE TITLE
Dans HELP.html, les liens pour l'édition (sur github) sont remplacés par des liens internes

### ISSUE THREAD

**Issue by sveinburne** [dirtylab/site-scripts#7]
[Voici la page qui pose problème](http://dirtylab.github.io/HELP.html)

**Comment by Frosty-Z** [comment]
Je viens de faire les corrections, ça devrait être bon lors du prochain push

**Comment by sveinburne** [comment]
Toujours apparent en ligne comme en local

**Comment by Frosty-Z** [comment]
Ok, je n'avais pas bien compris le problème à la base ^^

En gros là on veut faire une exception au fonctionnement de base consistant à faire en sorte que les .MD sur GitHub soient les pages d'un site statique.
Pour éviter un gros hack tout moche (du style ˋ(MACHIN.MD***interne***)ˋ) je dois pouvoir faire en sorte, pas trop difficilement, que les liens absolus (http(s)://...) ne soient pas touchés par le process, seuls les liens relatifs, et du même coup ça corrigerait le #8.

**Comment by Frosty-Z** [comment]
Et je testerai sur Ubuntu :penguin: :smirk:

**Comment by Frosty-Z** [comment]
Bon ˋsedˋ s'avère trop limité (besoin de "negative lookahead") ; il va falloir que je passe à quelque chose de plus sérieux. Je vais essayer avec PHP et son support des PCRE, d'autant que je suis habitué à cette techno et que c'est déjà utilisé pour la gestion des emoji.

**Comment by sveinburne** [comment]
@Frosty-Z tu pourrais sinon tester après le matching de sed si le string capturé matche `^http:\/\/.*$`

**Comment by sveinburne** [comment]
@Frosty-Z ah non j'ai rien dit -_- c'est couplé à une commande de remplacement

**Comment by Frosty-Z** [comment]
@sveinburne 

En effet, avec `sed` le fichier est modifié direct, pas de "traitement intermédiaire" possible (ou alors galère, je connais pas assez).

Bref, ça doit être bon. J'ai vérifié sur Ubuntu, mais je te laisse quand même vérifier et fermer le bug si Ok pour toi.

**Comment by sveinburne** [comment]
Ok excellent, ça marche !
