### ISSUE TITLE
Limiter la conversion .MD à .html aux chemins relatifs

### ISSUE THREAD

**Issue by sveinburne** [dirtylab/site-scripts#8]
[Exemple sur cette page](http://dirtylab.github.io/HELP.html) : le lien vers https://github.com/sveinburne/lets-play-science/blob/master/README.MD est remplacé par https://github.com/sveinburne/lets-play-science/blob/master/README.html

**Comment by Frosty-Z** [comment]
Oui. Le lien n'avait pas besoin d'être en absolu, donc corrigé, mais c'est sûr que si on "pointe" vers des .MD "externes" la regexp actuelle posera problème, et reste à peaufiner.

**Comment by Frosty-Z** [comment]
@sveinburne 
Ca doit être bon. Je te laisse vérifier et fermer le bug si Ok pour toi
